import { SPORTS } from './constants'

export const matches = [
  {
    id: 1,
    sport: SPORTS.SOCCER,
    league: 'K리그1',
    homeTeam: '울산 현대',
    awayTeam: '전북 현대',
    startTime: '18:00',
    date: '2월 27일',
    odds: { home: 2.15, draw: 3.20, away: 3.45 },
  },
  {
    id: 2,
    sport: SPORTS.SOCCER,
    league: 'EPL',
    homeTeam: '맨체스터 유나이티드',
    awayTeam: '리버풀',
    startTime: '21:00',
    date: '2월 27일',
    odds: { home: 2.80, draw: 3.40, away: 2.35 },
  },
  {
    id: 3,
    sport: SPORTS.BASEBALL,
    league: 'KBO',
    homeTeam: 'LG 트윈스',
    awayTeam: '삼성 라이온즈',
    startTime: '18:30',
    date: '2월 27일',
    odds: { home: 1.85, draw: 0, away: 2.10 },
  },
  {
    id: 4,
    sport: SPORTS.SOCCER,
    league: '라리가',
    homeTeam: '레알 마드리드',
    awayTeam: '바르셀로나',
    startTime: '04:00',
    date: '2월 28일',
    odds: { home: 2.10, draw: 3.50, away: 3.20 },
  },
  {
    id: 5,
    sport: SPORTS.BASKETBALL,
    league: 'KBL',
    homeTeam: '서울 SK',
    awayTeam: '전주 KCC',
    startTime: '19:00',
    date: '2월 27일',
    odds: { home: 1.75, draw: 0, away: 2.15 },
  },
  {
    id: 6,
    sport: SPORTS.VOLLEYBALL,
    league: 'V리그',
    homeTeam: '대한항공',
    awayTeam: '삼성화재',
    startTime: '19:00',
    date: '2월 27일',
    odds: { home: 1.90, draw: 0, away: 2.00 },
  },
]
